<<<<<<< HEAD
[general]
import = [
    "~/.config/alacritty/themes/kanagawa_wave.toml"
=======
<<<<<<< HEAD
import = [
    "~/.config/alacritty/themes/kanagawa_dragon.toml"
=======
[general]
import = [
    "~/.config/alacritty/themes/kanagawa_wave.toml"
>>>>>>> d2862f4 (new files from mac)
>>>>>>> 444d7a2 (add README.md and zsh)
#
# DOWNLOAD FROM:
# https://github.com/alacritty/alacritty-theme
#
# THEMES:
#
# SOFT COLORS:
#
# - autumn
# - citylights
# - wombat
# - tomorrow_night
# - taerminal
# - remedy_dark
# - monokai_pro
# - kanagawa_dragon
# - kanagawa_wave
# - everforest_dark
# - gruvbox_dark
# - gruvbox_material_hard_dark
#
# CONTRAST COLORS:
#
# - ayu_dark
#
# VIVID:
#
# - catppuccin_mocha
# - enfocado_dark
# - rose_pine
# - palenight
# - night_owl
#
# GREY:
#
# - doom_one 
# - nordic
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"


[window]
<<<<<<< HEAD
padding.x = 5
padding.y = 5
=======
<<<<<<< HEAD
padding.x = 2
padding.y = 2
>>>>>>> 444d7a2 (add README.md and zsh)

decorations = "Buttonless" # Full, Transparent, Buttonless, None
opacity = 0.9
blur = false
startup_mode = "Windowed"

[font]
normal.family = "Hack Nerd Font"
size = 15.0

<<<<<<< HEAD
=======
[shell]
program = "/bin/zsh"
=======
padding.x = 5
padding.y = 5

decorations = "Buttonless" # Full, Transparent, Buttonless, None
opacity = 0.9
blur = false
startup_mode = "Windowed"

[font]
normal.family = "Hack Nerd Font"
size = 15.0

>>>>>>> 444d7a2 (add README.md and zsh)
# Перемещение по словам через Alt + -> / <-
[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

# Не перехватывать Option+Space в Alacritty, отдать системе (Spotlight/Alfred)
[[keyboard.bindings]]
key = "Space"
mods = "Alt"
action = "None"

[terminal]
shell = "/bin/zsh"
<<<<<<< HEAD
=======
>>>>>>> d2862f4 (new files from mac)
>>>>>>> 444d7a2 (add README.md and zsh)
