#!usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ---------- глобальные настройки ----------
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              0.8            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                off             \
    skip_window_focus_animation  on            \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.80           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  5             \
    bottom_padding               5             \
    left_padding                 5             \
    right_padding                5             \
    window_gap                   5             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# ---------- rules ----------

# Alacritty Space 1 
yabai -m rule --add app="^Alacritty$" space=^1 manage=on

# apps to not manage (ignore)
yabai -m rule --add app="^Red Shield VPN$" manage=off
yabai -m rule --add app="^Системные настройки$" manage=off
yabai -m rule --add app="^KeyboardCleanTool$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off


# отключение вывода логов
yabai -m config debug_output off

echo "yabai configuration loaded.."
