set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g mouse on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g status-style 'bg=#333333 fg=#5eacd3'
set -g base-index 1

# vi-режим в copy-mode
set -g mode-keys vi
# Visual mode (v) и копирование в системный буфер (y)
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# сначала убираем стандартные бинды %, "
unbind %
unbind '"'
# наши сплиты
bind - split-window -h   # вертикальный сплит (одна панель над другой)
bind _ split-window -v   # горизонтальный сплит (панели рядом)



### СТИЛЬ ###
# базовый стиль бара
set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-style "bg=#101113 fg=#9f9e99"   # main bg + main fg

# стиль строки окон
set -g window-status-format " #I #W "
set -g window-status-current-format "#[bg=#83799C fg=#101113] #I #W #[default]"
#           griffith_purple         rainy_night_black_1

# приглушённые неактивные окна
set -g window-status-style "bg=#161719 fg=#787487"
#                          rainy_night_black_2   dragon_slayer_gray_2
set -g window-status-current-style "bold"

# слева — имя сессии
set -g status-left "#[bg=#787487 fg=#101113] #S #[default] "
#                  campfire       rainy_night_black_1
set -g status-left-length 32


# справа индикатор префикса 
set -g status-right " #{?client_prefix,#[fg=#83799C]⌨ #[default],} "

